name: Build macOS .app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        # Install any dependencies you need here
        # For example: brew install some-dependency
        echo "Setting up dependencies..."

    - name: Build the project
      run: |
        # Run your build commands here
        # Example: ./build.sh
        echo "Building project..."
        mkdir -p ./build  # Ensure the build directory exists
        touch ./build/SuperMario64.app  # Dummy file for testing (replace with actual build command)

    - name: Debug build output
      run: |
        echo "Verifying build output..."
        ls -al ./build

    - name: Upload macOS .app
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: ./build/SuperMario64.app
